# Generated by Django 6.1.1 on 2026-10-06 11:14

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nic', models.CharField(blank=True, max_length=12, null=True, verbose_name='NIC')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('designation', models.CharField(help_text='e.g. Staff Nurse, Porter', max_length=100)),
                ('category', models.CharField(choices=[('MEDICAL', 'Medical'), ('NURSING', 'Nursing'), ('ALLIED_HEALTH', 'Allied health'), ('ADMINISTRATIVE', 'Administrative'), ('SUPPORT', 'Support')], max_length=20)),
                ('employment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary')], max_length=20)),
                ('date_joined', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='doctors.department')),
                ('user', models.OneToOneField(blank=True, help_text='Optional. Lets this person request leave themselves.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Login account')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('HALF_DAY', 'Half day'), ('ABSENT', 'Absent')], max_length=10)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='staff.employee')),
            ],
            options={
                'verbose_name_plural': 'attendance',
                'ordering': ['-date', 'employee__first_name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('ANNUAL', 'Annual'), ('CASUAL', 'Casual'), ('SICK', 'Sick'), ('MATERNITY', 'Maternity'), ('NO_PAY', 'No pay'), ('OTHER', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='staff.employee')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nic'), condition=models.Q(('nic__isnull', False)), name='staff_employee_nic_ci_unique', violation_error_message='An employee with this NIC already exists.'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_date__isnull', True), ('status', 'ACTIVE')), models.Q(models.Q(('status', 'ACTIVE'), _negated=True), ('end_date__isnull', False)), _connector='OR'), name='staff_employee_end_date_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('date_joined')), _connector='OR'), name='staff_employee_end_after_join', violation_error_message="The end date can't be before the joining date."),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='staff_attendance_one_per_day', violation_error_message='Attendance for this employee and day already exists.'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(('check_in__isnull', True), ('check_out__isnull', True), ('check_out__gt', models.F('check_in')), _connector='OR'), name='staff_attendance_out_after_in', violation_error_message='Check-out must be after check-in.'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ABSENT'), _negated=True), models.Q(('check_in__isnull', True), ('check_out__isnull', True)), _connector='OR'), name='staff_attendance_absent_has_no_times', violation_error_message='An absent employee has no check-in or check-out time.'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='staff_leave_end_after_start', violation_error_message="The last day can't be before the first day."),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('decision_note', ''), _negated=True), _connector='OR'), name='staff_leave_rejection_needs_note', violation_error_message='Give a reason for rejecting the leave.'),
        ),
    ]
