# Generated by Django 6.1.1 on 2026-10-03 16:54

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_by', models.CharField(blank=True, help_text='Referring doctor or clinic for walk-in requests', max_length=150)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent')], default='ROUTINE', max_length=10)),
                ('clinical_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SAMPLE_COLLECTED', 'Sample collected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('sample_collected_at', models.DateTimeField(blank=True, null=True)),
                ('sample_notes', models.CharField(blank=True, max_length=255)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ordering_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='patients.patient')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='records.medicalrecord')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sample_collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lab_order_link', to='patients.patientdocument')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='laboratory.laborder')),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code, e.g. FBC', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('section', models.CharField(choices=[('HAEMATOLOGY', 'Haematology'), ('BIOCHEMISTRY', 'Biochemistry'), ('MICROBIOLOGY', 'Microbiology'), ('IMMUNOLOGY', 'Immunology'), ('URINALYSIS', 'Urinalysis'), ('HISTOPATHOLOGY', 'Histopathology'), ('OTHER', 'Other')], max_length=20)),
                ('specimen_type', models.CharField(choices=[('BLOOD', 'Blood'), ('SERUM', 'Serum'), ('PLASMA', 'Plasma'), ('URINE', 'Urine'), ('STOOL', 'Stool'), ('SWAB', 'Swab'), ('SPUTUM', 'Sputum'), ('CSF', 'CSF'), ('TISSUE', 'Tissue'), ('OTHER', 'Other')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('turnaround_hours', models.PositiveSmallIntegerField(default=24)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section', 'name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='laboratory_labtest_code_ci_unique', violation_error_message='A test with this code already exists.'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='laboratory_labtest_price_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField(blank=True, verbose_name='Interpretation / comment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laboratory.laborder')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='laboratory.labtest')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='LabTestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('result_type', models.CharField(choices=[('NUMERIC', 'Number'), ('TEXT', 'Text')], default='NUMERIC', max_length=10)),
                ('ref_low', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ref_high', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ref_text', models.CharField(blank=True, help_text='e.g. "Negative"', max_length=100, verbose_name='Reference (text)')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='laboratory.labtest')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('value_text', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('ref_low', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ref_high', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ref_text', models.CharField(blank=True, max_length=100)),
                ('flag', models.CharField(blank=True, choices=[('L', 'Low'), ('H', 'High'), ('N', 'Normal'), ('', '—')], max_length=1)),
                ('entered_at', models.DateTimeField()),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.laborderitem')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='laboratory.labtestparameter')),
            ],
            options={
                'ordering': ['parameter__display_order', 'parameter_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='laborder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ordering_doctor__isnull', False), ('record__isnull', False)), models.Q(('referred_by', ''), _negated=True), _connector='OR'), name='laboratory_order_has_requester', violation_error_message='An order needs a consultation and doctor, or a referrer.'),
        ),
        migrations.AddConstraint(
            model_name='laborderitem',
            constraint=models.UniqueConstraint(fields=('order', 'test'), name='laboratory_item_unique_test', violation_error_message='This test is already on the order.'),
        ),
        migrations.AddConstraint(
            model_name='laborderitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='laboratory_item_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='labtestparameter',
            constraint=models.UniqueConstraint(models.F('test'), django.db.models.functions.text.Lower('name'), name='laboratory_parameter_name_unique_per_test', violation_error_message='This test already has a parameter with that name.'),
        ),
        migrations.AddConstraint(
            model_name='labtestparameter',
            constraint=models.CheckConstraint(condition=models.Q(('ref_low__isnull', True), ('ref_high__isnull', True), ('ref_low__lte', models.F('ref_high')), _connector='OR'), name='laboratory_parameter_range_order', violation_error_message='The low reference value must not be above the high one.'),
        ),
        migrations.AddConstraint(
            model_name='labresult',
            constraint=models.UniqueConstraint(fields=('item', 'parameter'), name='laboratory_result_unique_parameter'),
        ),
    ]
