# Generated by Django 6.1.1 on 2026-10-03 10:44

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('generic_name', models.CharField(blank=True, max_length=150)),
                ('form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('SUSPENSION', 'Suspension'), ('INJECTION', 'Injection'), ('INFUSION', 'Infusion'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('OTHER', 'Other')], max_length=20)),
                ('strength', models.CharField(help_text='e.g. 500 mg or 5 mg/5 ml', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'strength'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('strength'), models.F('form'), name='pharmacy_medicine_unique', violation_error_message='This medicine (name, strength and form) already exists.')],
            },
        ),
    ]
