# Generated by Django 6.1.1 on 2026-10-05 07:23

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('pharmacy', '0001_initial'),
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-dispensed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DispenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('quantity_received', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_on_hand', models.PositiveIntegerField()),
                ('supplier', models.CharField(blank=True, max_length=150)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'stock batches',
                'ordering': ['expiry_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RECEIVE', 'Received'), ('DISPENSE', 'Dispensed'), ('ADJUSTMENT', 'Adjustment'), ('EXPIRY_WRITE_OFF', 'Expiry write-off')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='reorder_level',
            field=models.PositiveIntegerField(default=10, help_text='Warn when usable stock falls to this many units'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per tablet, capsule, bottle, ...', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Unit price (Rs.)'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='pharmacy_medicine_unit_price_non_negative'),
        ),
        migrations.AddField(
            model_name='dispense',
            name='dispensed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispense',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='dispense',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='records.prescription'),
        ),
        migrations.AddField(
            model_name='dispenseitem',
            name='dispense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.dispense'),
        ),
        migrations.AddField(
            model_name='dispenseitem',
            name='prescription_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_items', to='records.prescriptionitem'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='pharmacy.medicine'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='pharmacy.stockbatch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='dispense_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='pharmacy.dispenseitem'),
        ),
        migrations.AddConstraint(
            model_name='dispenseitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='pharmacy_dispense_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='dispenseitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='pharmacy_dispense_item_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.UniqueConstraint(models.F('medicine'), django.db.models.functions.text.Lower('batch_number'), name='pharmacy_batch_number_unique_per_medicine', violation_error_message='This batch number already exists for this medicine. Adding more to an existing batch is not supported; record the delivery with its own batch number.'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gt', 0)), name='pharmacy_batch_received_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__lte', models.F('quantity_received'))), name='pharmacy_batch_on_hand_within_received'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='pharmacy_movement_non_zero'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'RECEIVE'), _negated=True), ('quantity__gt', 0), _connector='OR'), name='pharmacy_movement_receive_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type__in', ['DISPENSE', 'EXPIRY_WRITE_OFF']), _negated=True), ('quantity__lt', 0), _connector='OR'), name='pharmacy_movement_out_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'DISPENSE'), _negated=True), ('dispense_item__isnull', False), _connector='OR'), name='pharmacy_movement_dispense_has_item'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type__in', ['ADJUSTMENT', 'EXPIRY_WRITE_OFF']), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='pharmacy_movement_reason_required'),
        ),
    ]
