# Generated by Django 6.1.1 on 2026-10-05 12:53

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ward__name', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('OPD', 'Outpatient appointment'), ('EMERGENCY', 'Emergency'), ('REFERRAL', 'Referral'), ('DIRECT', 'Direct')], max_length=20)),
                ('reason', models.TextField(verbose_name='Reason for admission')),
                ('status', models.CharField(choices=[('ADMITTED', 'Admitted'), ('DISCHARGED', 'Discharged')], default='ADMITTED', max_length=20)),
                ('admitted_at', models.DateTimeField()),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_type', models.CharField(blank=True, choices=[('HOME', 'Discharged home'), ('TRANSFERRED_OUT', 'Transferred to another hospital'), ('AGAINST_MEDICAL_ADVICE', 'Left against medical advice'), ('DECEASED', 'Deceased')], max_length=30)),
                ('discharge_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('admitting_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='doctors.doctor')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='appointments.appointment')),
                ('discharged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='patients.patient')),
            ],
            options={
                'ordering': ['-admitted_at'],
            },
        ),
        migrations.CreateModel(
            name='BedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='admissions.admission')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='admissions.bed')),
            ],
            options={
                'ordering': ['started_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('DOCTOR_ROUND', "Doctor's round"), ('NURSING', 'Nursing'), ('OTHER', 'Other')], max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='admissions.admission')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ward_type', models.CharField(choices=[('GENERAL', 'General'), ('ICU', 'ICU'), ('MATERNITY', 'Maternity'), ('PAEDIATRIC', 'Paediatric'), ('SURGICAL', 'Surgical'), ('PRIVATE', 'Private')], max_length=20)),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Charged per night in a bed of this ward', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Daily rate (Rs.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='doctors.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='admissions.ward'),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ADMITTED')), fields=('patient',), name='admissions_one_current_admission_per_patient', violation_error_message='This patient is already admitted.'),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discharge_type', ''), ('discharged_at__isnull', True), ('status', 'ADMITTED')), models.Q(('discharged_at__isnull', False), ('status', 'DISCHARGED'), models.Q(('discharge_type', ''), _negated=True)), _connector='OR'), name='admissions_discharge_fields_consistent'),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.CheckConstraint(condition=models.Q(('discharged_at__isnull', True), ('discharged_at__gt', models.F('admitted_at')), _connector='OR'), name='admissions_discharged_after_admitted', violation_error_message='Discharge must be after admission.'),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source', 'OPD'), _negated=True), ('appointment__isnull', False), _connector='OR'), name='admissions_opd_needs_appointment', violation_error_message='Admissions from an outpatient visit need the appointment.'),
        ),
        migrations.AddConstraint(
            model_name='bedassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('bed',), name='admissions_one_open_assignment_per_bed', violation_error_message='This bed is occupied.'),
        ),
        migrations.AddConstraint(
            model_name='bedassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('admission',), name='admissions_one_open_assignment_per_admission'),
        ),
        migrations.AddConstraint(
            model_name='bedassignment',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='admissions_assignment_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='admissions_ward_name_ci_unique', violation_error_message='A ward with this name already exists.'),
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.CheckConstraint(condition=models.Q(('daily_rate__gte', 0)), name='admissions_ward_daily_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(models.F('ward'), django.db.models.functions.text.Lower('bed_number'), name='admissions_bed_number_unique_per_ward', violation_error_message='This ward already has a bed with that number.'),
        ),
    ]
