# Generated by Django 6.1.1 on 2026-10-02 00:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        # Existing users (the superuser created before roles existed) get ADMIN.
        # preserve_default=False uses the default only to fill existing rows; the field
        # itself keeps no default, so new users must be given a role explicitly.
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('RECEPTIONIST', 'Receptionist'), ('LAB_STAFF', 'Lab Staff'), ('PHARMACIST', 'Pharmacist'), ('ACCOUNTANT', 'Accountant')], default='ADMIN', max_length=20),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['ADMIN', 'DOCTOR', 'NURSE', 'RECEPTIONIST', 'LAB_STAFF', 'PHARMACIST', 'ACCOUNTANT'])), name='accounts_user_role_valid'),
        ),
    ]
