# Generated by Django 6.1.1 on 2026-10-03 10:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=10)),
                ('presenting_complaint', models.TextField()),
                ('clinical_notes', models.TextField(blank=True)),
                ('examination_findings', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='medical_record', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIALLY_DISPENSED', 'Partially dispensed'), ('DISPENSED', 'Dispensed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prescription', to='records.medicalrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordAddendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addenda', to='records.medicalrecord')),
            ],
            options={
                'verbose_name_plural': 'record addenda',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='record_link', to='patients.patientdocument')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('icd10_code', models.CharField(blank=True, help_text='Optional, e.g. J45 or J45.909', max_length=10, verbose_name='ICD-10 code')),
                ('diagnosis_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], default='PRIMARY', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='records.medicalrecord')),
            ],
            options={
                'verbose_name_plural': 'diagnoses',
                'ordering': ['diagnosis_type', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('diagnosis_type', 'PRIMARY')), fields=('record',), name='records_one_primary_diagnosis', violation_error_message='This consultation already has a primary diagnosis.')],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(help_text='e.g. 1 tablet or 5 ml', max_length=50)),
                ('frequency', models.CharField(choices=[('OD', 'Once daily'), ('BD', 'Twice daily'), ('TDS', 'Three times daily'), ('QDS', 'Four times daily'), ('NOCTE', 'At night'), ('MANE', 'In the morning'), ('STAT', 'Immediately (once)'), ('PRN', 'When required'), ('Q4H', 'Every 4 hours'), ('Q6H', 'Every 6 hours'), ('Q8H', 'Every 8 hours'), ('WEEKLY', 'Once weekly')], max_length=10)),
                ('route', models.CharField(choices=[('ORAL', 'Oral'), ('SUBLINGUAL', 'Sublingual'), ('IV', 'Intravenous (IV)'), ('IM', 'Intramuscular (IM)'), ('SC', 'Subcutaneous (SC)'), ('TOPICAL', 'Topical'), ('INHALED', 'Inhaled'), ('RECTAL', 'Rectal'), ('OPHTHALMIC', 'Eye (ophthalmic)'), ('OTIC', 'Ear (otic)'), ('NASAL', 'Nasal'), ('OTHER', 'Other')], default='ORAL', max_length=12)),
                ('duration_days', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration (days)')),
                ('quantity', models.PositiveIntegerField(help_text='Total units to dispense', validators=[django.core.validators.MinValueValidator(1)])),
                ('instructions', models.CharField(blank=True, help_text='e.g. after meals', max_length=255)),
                ('allergy_override', models.BooleanField(default=False)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='pharmacy.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='records.prescription')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='records_item_quantity_positive', violation_error_message='Quantity must be at least 1.'), models.CheckConstraint(condition=models.Q(('duration_days__gt', 0)), name='records_item_duration_positive', violation_error_message='Duration must be at least 1 day.'), models.UniqueConstraint(fields=('prescription', 'medicine'), name='records_item_unique_medicine', violation_error_message='This medicine is already on the prescription.')],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(260)], verbose_name='BP systolic (mmHg)')),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(160)], verbose_name='BP diastolic (mmHg)')),
                ('pulse_bpm', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(250)], verbose_name='Pulse (bpm)')),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)], verbose_name='Respiratory rate (/min)')),
                ('spo2_percent', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)], verbose_name='SpO₂ (%)')),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('30.0')), django.core.validators.MaxValueValidator(Decimal('45.0'))], verbose_name='Temperature (°C)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('500'))], verbose_name='Weight (kg)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('30')), django.core.validators.MaxValueValidator(Decimal('250'))], verbose_name='Height (cm)')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vitals', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='patients.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'vitals',
                'constraints': [models.CheckConstraint(condition=models.Q(('bp_systolic__isnull', True), models.Q(('bp_systolic__gte', 50), ('bp_systolic__lte', 260)), _connector='OR'), name='records_vitals_bp_systolic_range'), models.CheckConstraint(condition=models.Q(('bp_diastolic__isnull', True), models.Q(('bp_diastolic__gte', 30), ('bp_diastolic__lte', 160)), _connector='OR'), name='records_vitals_bp_diastolic_range'), models.CheckConstraint(condition=models.Q(('pulse_bpm__isnull', True), models.Q(('pulse_bpm__gte', 20), ('pulse_bpm__lte', 250)), _connector='OR'), name='records_vitals_pulse_bpm_range'), models.CheckConstraint(condition=models.Q(('respiratory_rate__isnull', True), models.Q(('respiratory_rate__gte', 5), ('respiratory_rate__lte', 60)), _connector='OR'), name='records_vitals_respiratory_rate_range'), models.CheckConstraint(condition=models.Q(('spo2_percent__isnull', True), models.Q(('spo2_percent__gte', 50), ('spo2_percent__lte', 100)), _connector='OR'), name='records_vitals_spo2_percent_range'), models.CheckConstraint(condition=models.Q(('temperature_c__isnull', True), models.Q(('temperature_c__gte', Decimal('30.0')), ('temperature_c__lte', Decimal('45.0'))), _connector='OR'), name='records_vitals_temperature_c_range'), models.CheckConstraint(condition=models.Q(('weight_kg__isnull', True), models.Q(('weight_kg__gte', Decimal('0.5')), ('weight_kg__lte', Decimal('500'))), _connector='OR'), name='records_vitals_weight_kg_range'), models.CheckConstraint(condition=models.Q(('height_cm__isnull', True), models.Q(('height_cm__gte', Decimal('30')), ('height_cm__lte', Decimal('250'))), _connector='OR'), name='records_vitals_height_cm_range'), models.CheckConstraint(condition=models.Q(('bp_systolic__isnull', True), ('bp_diastolic__isnull', True), ('bp_systolic__gt', models.F('bp_diastolic')), _connector='OR'), name='records_vitals_systolic_above_diastolic', violation_error_message='Systolic pressure must be higher than diastolic.')],
            },
        ),
    ]
