# Generated by Django 6.1.1 on 2026-10-02 09:40

import django.db.models.deletion
import django.db.models.functions.text
import patients.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('nic', models.CharField(blank=True, max_length=12, null=True, verbose_name='NIC')),
                ('phone', models.CharField(help_text='e.g. 0771234567 or +94771234567', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('allergies', models.TextField(blank=True, help_text='Leave blank if none known')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=patients.models.patient_document_path)),
                ('original_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('LAB_REPORT', 'Lab report'), ('PRESCRIPTION', 'Prescription'), ('IMAGING', 'Imaging'), ('REFERRAL', 'Referral'), ('DISCHARGE_SUMMARY', 'Discharge summary'), ('ID_DOCUMENT', 'ID document'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(max_length=50)),
                ('size_bytes', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nic'), condition=models.Q(('nic__isnull', False)), name='patients_patient_nic_ci_unique', violation_error_message='A patient with this NIC is already registered.'),
        ),
    ]
